### ISSUE TITLE
Function to scale value between ranges.

### ISSUE THREAD

**Issue by cos1110** [wonkey-coders/wonkey#8]
```
#rem wonkeydoc Scale a value from an initial range to a target range.
@param `start1` The initial start value.
@param `stop1` The initial stop value.
@param `start2` The target start value.
@param `stop2` The target stop value.
@return The input `value` scaled from (`start1`-`stop1`) to (`start2`-`stop2`).
#end
Function Scale:Float(value:Float, start1:Float, stop1:Float, start2:Float, stop2:Float)
	Return Scale<Float>(value, start1, stop1, start2, stop2)
End

#rem wonkeydoc Scale a value from an initial range to a target range (generic version).
Remarks: `Scale:Int()` won't work, use `Float` instead and then cast to integer.
@param `start1` The initial start value.
@param `stop1` The initial stop value.
@param `start2` The target start value.
@param `stop2` The target stop value.
@return The input `value` scaled from (`start1`-`stop1`) to (`start2`-`stop2`).
#end
Function Scale<T>:T(value:T, start1:T, stop1:T, start2:T, stop2:T)
	Return start2 + (stop2 - start2) * ((value - start1) / (stop1 - start1))
End

Function TestScale()
	Print(Scale(128, 0, 255, 0.0, 1.0)) ' about 0.50
	For Local i := 0 To 10
		Print(Scale<Float>(i, 0, 10, 0, 1280))
	Next
End
```

**Comment by cos1110** [comment]
Suggested for `math.wx` line:390 etc...

**Comment by seyhajin** [comment]
We can restrict the type of generic by adding `Where T Implements IReal` (float and double) at the end of the function declaration `Scale<T>:T(...)` :

```monkey
Function Scale<T>:T(value:T, start1:T, stop1:T, start2:T, stop2:T) Where T Implements IReal
	Return start2 + (stop2 - start2) * ((value - start1) / (stop1 - start1))
End
```

And rename the `Scale:Float(...)` function to `Scalef:Float(...)`.

What do you think of this?

**Comment by cos1110** [comment]
Some extra thoughts on this:

* The first time I tried with a 100% generic version, this works great for Floats or Doubles, but not Integer. Users might get confused and try Int or Byte, etc, which makes things more complicated. At least that way the API can be locked into a fail-safe state.

* Obviously for integers one would have to do `Cast<Int>(Scale<Float>(...))`.

* By looking at `math.wx` I got inspired to add an overloaded a `Float` version as well. Though in terms of generic implementation is not needed. I wonder if it makes programming easier having extra implementations for `Float` and `Double`.

**Comment by seyhajin** [comment]
Ideally, we should be able to do this with any type of number `int` or `float`, in this case we could put `Where T Implements INumeric` instead of `... IReal`.

Also, one can convert directly to a primitive type by doing `Int(Scale<Float>(...))` instead of using the `Cast<Int>(...)` operator.

In my opinion, we should keep only the generic function and let the user do an overload if needed. I'll get it in as soon as possible :)

**Comment by seyhajin** [comment]
Finally I think to add only the function in `Double` (who can the more can the less). It is not useful to make a generic function for this and will leave the choice to the user to convert to `float` or `int`.

```monkey
#rem wonkeydoc Scale a value from an initial range to a target range.
    @param `start1` The initial start value.
    @param `stop1` The initial stop value.
    @param `start2` The target start value.
    @param `stop2` The target stop value.
    @return The input `value` scaled from (`start1`-`stop1`) to (`start2`-`stop2`).
#end
Function Scale:Double(value:Double, start1:Double, stop1:Double, start2:Double, stop2:Double) Where T Implements IReal
    Return start2 + (stop2 - start2) * ((value - start1) / (stop1 - start1))
End
```

**Comment by seyhajin** [comment]
Added in 7864dec and 4d87278 commits
